fault_duration_min: 10
fault_duration_max: 10
fault_amplitude_min: 1
fault_amplitude_max: 1
joint_names:
  - panda_joint1
  # - panda_joint2
  # - panda_joint3
  # - panda_joint4
  # - panda_joint5
  # - panda_joint6
  # - panda_joint7
  # - panda_joint8
